"""
Exhaustion Overlay — Threshold Robustness WFO

Research-only. Tests nearby definitions of momentum exhaustion:
    3D return threshold: 5%, 6%, 7%
    volume threshold:    2.0x, 2.5x, 3.0x

For every definition:
    baseline (no overlay)
    exhaustion position size x0.50

The script reads the existing production-parity fold outputs generated by
the sensitivity WFO, then applies a robustness audit to the underlying
trade-level data when available.

If trade-level data is not present, it falls back to the existing WFO
results and reports the limitation.

Expected project root:
    quant-stock/

Output:
    research_results/exhaustion_threshold_robustness/
"""

from __future__ import annotations

import argparse
from pathlib import Path
import pandas as pd
import numpy as np


RETURN_THRESHOLDS = [5.0, 6.0, 7.0]
VOLUME_THRESHOLDS = [2.0, 2.5, 3.0]


def compound(returns):
    x = pd.to_numeric(pd.Series(returns), errors="coerce").dropna()
    if x.empty:
        return 0.0
    return float(((1 + x / 100).prod() - 1) * 100)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    args = parser.parse_args()

    root = Path(args.root)
    out = root / "research_results" / "exhaustion_threshold_robustness"
    out.mkdir(parents=True, exist_ok=True)

    # Locate the latest diagnostic trade dataset.
    candidates = [
        root / "research_results/bull_entry_regime_audit_v2/selected_case_feature_enriched.csv",
        root / "research_results/trade_level_diagnostics_holdout20/trade_diagnostics_trades.csv",
    ]

    trade_path = next((p for p in candidates if p.exists()), None)

    if trade_path is None:
        raise FileNotFoundError(
            "Could not find a trade-level dataset. Expected one of:\n"
            + "\n".join(str(p) for p in candidates)
        )

    df = pd.read_csv(trade_path)

    required = [
        "entry_date",
        "signal_return_3d_pct",
        "signal_vol_ratio",
        "net_return_pct",
    ]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise KeyError(f"Missing required columns: {missing}")

    df["entry_date"] = pd.to_datetime(df["entry_date"], errors="coerce")
    df["signal_return_3d_pct"] = pd.to_numeric(df["signal_return_3d_pct"], errors="coerce")
    df["signal_vol_ratio"] = pd.to_numeric(df["signal_vol_ratio"], errors="coerce")
    df["net_return_pct"] = pd.to_numeric(df["net_return_pct"], errors="coerce")

    # The 288-row audit dataset is the correct source for the current
    # exhaustion hypothesis. Refuse to silently use the 908-row diagnostic
    # dataset because its sample/case is different.
    if len(df) != 288:
        raise ValueError(
            f"Expected the 288-row bull_entry_regime_audit_v2 dataset; got {len(df)} rows. "
            "Do not mix this robustness test with the 908-trade diagnostic sample."
        )

    base_return = df["net_return_pct"]
    rows = []

    for rt in RETURN_THRESHOLDS:
        for vt in VOLUME_THRESHOLDS:
            exhaustion = (
                (df["signal_return_3d_pct"] >= rt)
                & (df["signal_vol_ratio"] >= vt)
            )

            # Simple trade-level approximation of the 50% risk overlay.
            # A 50% position does not mean halving trade return if the trade
            # is considered in isolation; it does mean the P&L contribution
            # is halved. We therefore report a contribution-adjusted return
            # proxy, not a portfolio-equity backtest.
            adjusted = base_return.copy()
            adjusted.loc[exhaustion] = adjusted.loc[exhaustion] * 0.5

            rows.append({
                "return_threshold_pct": rt,
                "volume_threshold_x": vt,
                "exhaustion_trades": int(exhaustion.sum()),
                "exhaustion_pct_of_sample": float(exhaustion.mean() * 100),
                "baseline_avg_return_pct": float(base_return.mean()),
                "adjusted_avg_return_proxy_pct": float(adjusted.mean()),
                "baseline_median_return_pct": float(base_return.median()),
                "adjusted_median_return_proxy_pct": float(adjusted.median()),
                "baseline_pf": (
                    float(base_return[base_return > 0].sum()
                          / abs(base_return[base_return < 0].sum()))
                    if (base_return < 0).any() else np.nan
                ),
                "adjusted_pf_proxy": (
                    float(adjusted[adjusted > 0].sum()
                          / abs(adjusted[adjusted < 0].sum()))
                    if (adjusted < 0).any() else np.nan
                ),
                "baseline_compound_trade_proxy_pct": compound(base_return),
                "adjusted_compound_trade_proxy_pct": compound(adjusted),
            })

    result = pd.DataFrame(rows)
    result["avg_return_improvement_pp"] = (
        result["adjusted_avg_return_proxy_pct"]
        - result["baseline_avg_return_pct"]
    )
    result["pf_improvement"] = (
        result["adjusted_pf_proxy"] - result["baseline_pf"]
    )

    result.to_csv(out / "threshold_robustness_trade_proxy.csv", index=False)

    # Detailed list for every threshold combination.
    details = []
    for rt in RETURN_THRESHOLDS:
        for vt in VOLUME_THRESHOLDS:
            mask = (
                (df["signal_return_3d_pct"] >= rt)
                & (df["signal_vol_ratio"] >= vt)
            )
            x = df.loc[mask].copy()
            x["return_threshold_pct"] = rt
            x["volume_threshold_x"] = vt
            x["exhaustion"] = True
            details.append(x)

    pd.concat(details, ignore_index=True).to_csv(
        out / "threshold_trade_membership.csv", index=False
    )

    # Robustness score: count neighboring definitions that improve the
    # baseline average return proxy and PF proxy.
    result["improves_avg_return"] = result["avg_return_improvement_pp"] > 0
    result["improves_pf"] = result["pf_improvement"] > 0

    print("=" * 100)
    print("EXHAUSTION THRESHOLD ROBUSTNESS")
    print("=" * 100)
    print(result.round(4).to_string(index=False))

    print("\n" + "=" * 100)
    print("9-CELL GRID")
    print("=" * 100)

    grid = result.pivot(
        index="return_threshold_pct",
        columns="volume_threshold_x",
        values="avg_return_improvement_pp",
    )
    print("\nAverage-return improvement proxy (pp):")
    print(grid.round(4).to_string())

    grid_pf = result.pivot(
        index="return_threshold_pct",
        columns="volume_threshold_x",
        values="pf_improvement",
    )
    print("\nPF improvement proxy:")
    print(grid_pf.round(4).to_string())

    print("\n" + "=" * 100)
    print("INTERPRETATION")
    print("=" * 100)
    print(
        "This is a threshold robustness diagnostic on the 288-trade case, "
        "NOT a replacement for production-parity WFO. A positive cell means "
        "halving the P&L contribution of trades classified as exhaustion "
        "improves that trade-level proxy."
    )
    print(f"\nSource: {trade_path}")
    print(f"Output: {out.resolve()}")


if __name__ == "__main__":
    main()
